import { describe, it, expect } from "vitest";
import { render, screen } from "@testing-library/react";
import {
  DenominationMode,
  formatCurrency,
  JournalMode,
  PayslipMode,
  PayrollRegisterMode,
  PrintFooter,
  PrintHeader,
  TransmittalMode,
} from "./";
import type { ProcessingRow } from "./PayrollOutputView.types";

// Mock lucide-react icons
vi.mock("lucide-react", () => ({
  Printer: () => <svg data-testid="icon-printer" />,
  FileSpreadsheet: () => <svg data-testid="icon-spreadsheet" />,
  Download: () => <svg data-testid="icon-download" />,
  Filter: () => <svg data-testid="icon-filter" />,
  Columns: () => <svg data-testid="icon-columns" />,
}));

// Mock Button component
vi.mock("@/components/ui/Button", () => ({
  Button: ({
    children,
    onClick,
    variant,
    size,
    className,
  }: {
    children: React.ReactNode;
    onClick?: () => void;
    variant?: string;
    size?: string;
    className?: string;
  }) => (
    <button
      onClick={onClick}
      data-variant={variant}
      data-size={size}
      className={className}
    >
      {children}
    </button>
  ),
}));

// Mock Card components
vi.mock("@/components/ui/Card", () => ({
  Card: ({
    children,
    className,
  }: {
    children: React.ReactNode;
    className?: string;
  }) => (
    <div data-testid="card" className={className}>
      {children}
    </div>
  ),
  CardHeader: ({ children }: { children: React.ReactNode }) => (
    <div data-testid="card-header">{children}</div>
  ),
  CardTitle: ({ children }: { children: React.ReactNode }) => (
    <h3 data-testid="card-title">{children}</h3>
  ),
  CardContent: ({
    children,
    className,
  }: {
    children: React.ReactNode;
    className?: string;
  }) => (
    <div data-testid="card-content" className={className}>
      {children}
    </div>
  ),
}));

describe("formatCurrency", () => {
  it("formats a number with 2 decimal places", () => {
    expect(formatCurrency(1234.5)).toBe("1,234.50");
  });

  it("formats zero correctly", () => {
    expect(formatCurrency(0)).toBe("0.00");
  });

  it("formats large numbers with commas", () => {
    expect(formatCurrency(1234567.89)).toBe("1,234,567.89");
  });

  it("rounds to 2 decimal places", () => {
    expect(formatCurrency(100.123)).toBe("100.12");
  });

  it("formats negative numbers", () => {
    expect(formatCurrency(-500.5)).toBe("-500.50");
  });
});

describe("PrintHeader", () => {
  const defaultProps = {
    company: { name: "Test Company" },
    payroll: { name: "Payroll January 2025", month: 1, year: 2025 },
    monthName: "January",
  };

  it("renders company name", () => {
    render(<PrintHeader {...defaultProps} />);
    expect(screen.getByText("Test Company")).toBeTruthy();
  });

  it("renders payroll name", () => {
    render(<PrintHeader {...defaultProps} />);
    expect(screen.getByText("Payroll January 2025")).toBeTruthy();
  });

  it("renders month and year", () => {
    render(<PrintHeader {...defaultProps} />);
    expect(screen.getByText("January 2025")).toBeTruthy();
  });

  it("renders fallback company name when company is undefined", () => {
    render(
      <PrintHeader
        company={undefined}
        payroll={defaultProps.payroll}
        monthName={defaultProps.monthName}
      />,
    );
    expect(screen.getByText("Company")).toBeTruthy();
  });
});

describe("PrintFooter", () => {
  it("renders default footer text when no company provided", () => {
    render(<PrintFooter company={undefined} />);
    expect(screen.getByText("Generated by Payroll System")).toBeTruthy();
  });

  it("renders custom print footer from company", () => {
    render(
      <PrintFooter company={{ name: "Test", printFooter: "Confidential" }} />,
    );
    expect(screen.getByText("Confidential")).toBeTruthy();
  });

  it("renders a date string", () => {
    render(<PrintFooter company={undefined} />);
    expect(screen.getByText(new Date().toLocaleDateString())).toBeTruthy();
  });
});

describe("PayrollRegisterMode", () => {
  const mockRows: ProcessingRow[] = [
    {
      nameId: "1",
      employeeCode: "EMP001",
      firstName: "John",
      lastName: "Doe",
      groupId: "grp1",
      positionId: "pos1",
      areaId: "area1",
      daysWorked: 20,
      absences: 1,
      lateHours: 2,
      overtimeHours: 5,
      basicSalary: 20000,
      ratePerDay: 1000,
      salaryAmount: 20000,
    },
  ];

  const defaultProps = {
    rows: mockRows,
    filteredRows: mockRows,
    earningData: new Map(),
    deductionData: new Map(),
    benefitData: new Map(),
    visibleColumns: {
      basic: true,
      earnings: true,
      gross: true,
      deductions: true,
      benefits: true,
      net: true,
      daysWorked: false,
      absences: false,
      late: false,
      overtime: false,
    },
    setVisibleColumns: () => {},
    showColumns: false,
    setShowColumns: () => {},
    showFilters: false,
    setShowFilters: () => {},
    filterGroup: "",
    setFilterGroup: () => {},
    filterPosition: "",
    setFilterPosition: () => {},
    filterArea: "",
    setFilterArea: () => {},
    groups: ["grp1"],
    positions: ["pos1"],
    areas: ["area1"],
    hasActiveFilters: false,
    activeFilterCount: 0,
    totals: {
      totalBasic: 20000,
      totalEarnings: 0,
      totalGross: 20000,
      totalDeductions: 0,
      totalBenefitsEE: 0,
      totalBenefitsER: 0,
      totalNet: 20000,
    },
    company: { name: "Test Company" },
    payroll: { name: "Payroll Jan", month: 1, year: 2025 },
    monthName: "January",
  };

  it("renders the Payroll Register title", () => {
    render(<PayrollRegisterMode {...defaultProps} />);
    expect(screen.getByText("Payroll Register")).toBeTruthy();
  });

  it("renders employee rows", () => {
    render(<PayrollRegisterMode {...defaultProps} />);
    expect(screen.getByText("EMP001")).toBeTruthy();
    expect(screen.getByText(/Doe/)).toBeTruthy();
  });

  it("renders total row when filteredRows has items", () => {
    render(<PayrollRegisterMode {...defaultProps} />);
    expect(screen.getByText(/1 employees/)).toBeTruthy();
  });

  it("shows 'No employees match' when filteredRows is empty", () => {
    render(<PayrollRegisterMode {...defaultProps} filteredRows={[]} />);
    expect(
      screen.getByText("No employees match the selected filters."),
    ).toBeTruthy();
  });

  it("renders filter button", () => {
    render(<PayrollRegisterMode {...defaultProps} />);
    expect(screen.getByText("Filters")).toBeTruthy();
  });

  it("renders columns button", () => {
    render(<PayrollRegisterMode {...defaultProps} />);
    expect(screen.getByText("Columns")).toBeTruthy();
  });
});

describe("TransmittalMode", () => {
  const mockRows: ProcessingRow[] = [
    {
      nameId: "1",
      employeeCode: "EMP001",
      firstName: "John",
      lastName: "Doe",
      groupId: "grp1",
      positionId: "pos1",
      areaId: "area1",
      daysWorked: 20,
      absences: 0,
      lateHours: 0,
      overtimeHours: 0,
      basicSalary: 20000,
      ratePerDay: 1000,
      salaryAmount: 20000,
    },
  ];

  const defaultProps = {
    rows: mockRows,
    getEmployeeNet: () => 20000,
    totals: { totalNet: 20000 },
    company: { name: "Test Company" },
    payroll: { name: "Payroll Jan", month: 1, year: 2025 },
    monthName: "January",
  };

  it("renders the title", () => {
    render(<TransmittalMode {...defaultProps} />);
    expect(screen.getByText("Bank Transmittal List")).toBeTruthy();
  });

  it("renders employee rows", () => {
    render(<TransmittalMode {...defaultProps} />);
    expect(screen.getByText("EMP001")).toBeTruthy();
  });
});

describe("JournalMode", () => {
  const defaultProps = {
    totals: {
      totalBasic: 20000,
      totalEarnings: 1000,
      totalBenefitsER: 500,
      totalBenefitsEE: 300,
      totalDeductions: 200,
      totalNet: 20500,
    },
    company: { name: "Test Company" },
    payroll: { name: "Payroll Jan", month: 1, year: 2025 },
    monthName: "January",
  };

  it("renders the title", () => {
    render(<JournalMode {...defaultProps} />);
    expect(screen.getByText("Journal Entry")).toBeTruthy();
  });

  it("renders salary expense", () => {
    render(<JournalMode {...defaultProps} />);
    expect(screen.getByText("Salaries & Wages Expense")).toBeTruthy();
  });
});

describe("DenominationMode", () => {
  const mockRows: ProcessingRow[] = [
    {
      nameId: "1",
      employeeCode: "EMP001",
      firstName: "John",
      lastName: "Doe",
      groupId: "grp1",
      positionId: "pos1",
      areaId: "area1",
      daysWorked: 20,
      absences: 0,
      lateHours: 0,
      overtimeHours: 0,
      basicSalary: 20000,
      ratePerDay: 1000,
      salaryAmount: 20000,
    },
  ];

  const defaultProps = {
    rows: mockRows,
    totals: { totalNet: 20000 },
    getEmployeeNet: () => 20000,
    company: { name: "Test Company" },
    payroll: { name: "Payroll Jan", month: 1, year: 2025 },
    monthName: "January",
  };

  it("renders the title", () => {
    render(<DenominationMode {...defaultProps} />);
    expect(screen.getByText("Cash Denomination Breakdown")).toBeTruthy();
  });

  it("renders denomination count section", () => {
    render(<DenominationMode {...defaultProps} />);
    expect(screen.getByText("Denomination Count")).toBeTruthy();
  });
});

describe("PayslipMode", () => {
  const mockRows: ProcessingRow[] = [
    {
      nameId: "1",
      employeeCode: "EMP001",
      firstName: "John",
      lastName: "Doe",
      groupId: "grp1",
      positionId: "pos1",
      areaId: "area1",
      daysWorked: 20,
      absences: 0,
      lateHours: 0,
      overtimeHours: 0,
      basicSalary: 20000,
      ratePerDay: 1000,
      salaryAmount: 20000,
    },
  ];

  const defaultProps = {
    rows: mockRows,
    filteredRows: mockRows,
    selectedEmployee: null,
    setSelectedEmployee: () => {},
    getEmployeeEarnings: () => [],
    getEmployeeDeductions: () => [],
    getEmployeeBenefits: () => [],
    getEmployeeNet: () => 20000,
    company: { name: "Test Company" },
    payroll: { name: "Payroll Jan", month: 1, year: 2025 },
    monthName: "January",
  };

  it("renders Employee Payslips title when no employee selected", () => {
    render(<PayslipMode {...defaultProps} />);
    expect(screen.getByText("Employee Payslips")).toBeTruthy();
  });

  it("renders Print All button", () => {
    render(<PayslipMode {...defaultProps} />);
    expect(screen.getByText(/Print All/)).toBeTruthy();
  });

  it("shows 'No employees' when rows are empty", () => {
    render(<PayslipMode {...defaultProps} rows={[]} filteredRows={[]} />);
    expect(screen.getByText("No employees in this payroll.")).toBeTruthy();
  });
});
