import { describe, it, expect } from "vitest";
import { render, screen } from "@testing-library/react";
import { formatCurrency, PrintHeader, PrintFooter } from "./shared";

describe("formatCurrency", () => {
  it("formats a number with 2 decimal places", () => {
    expect(formatCurrency(1234.5)).toBe("1,234.50");
  });

  it("formats zero correctly", () => {
    expect(formatCurrency(0)).toBe("0.00");
  });

  it("formats large numbers with commas", () => {
    expect(formatCurrency(1234567.89)).toBe("1,234,567.89");
  });

  it("rounds to 2 decimal places", () => {
    expect(formatCurrency(100.123)).toBe("100.12");
  });

  it("formats negative numbers", () => {
    expect(formatCurrency(-500.5)).toBe("-500.50");
  });

  it("formats whole numbers with .00", () => {
    expect(formatCurrency(500)).toBe("500.00");
  });

  it("formats small decimal values", () => {
    expect(formatCurrency(0.1)).toBe("0.10");
  });
});

describe("PrintHeader", () => {
  const defaultProps = {
    company: { name: "Test Company" },
    payroll: { name: "Payroll January 2025", month: 1, year: 2025 },
    monthName: "January",
  };

  it("renders company name", () => {
    render(<PrintHeader {...defaultProps} />);
    expect(screen.getByText("Test Company")).toBeTruthy();
  });

  it("renders payroll name", () => {
    render(<PrintHeader {...defaultProps} />);
    expect(screen.getByText("Payroll January 2025")).toBeTruthy();
  });

  it("renders month and year", () => {
    render(<PrintHeader {...defaultProps} />);
    expect(screen.getByText("January 2025")).toBeTruthy();
  });

  it("renders fallback company name when company is undefined", () => {
    render(
      <PrintHeader
        company={undefined}
        payroll={defaultProps.payroll}
        monthName={defaultProps.monthName}
      />,
    );
    expect(screen.getByText("Company")).toBeTruthy();
  });

  it("has hidden print:block class", () => {
    const { container } = render(<PrintHeader {...defaultProps} />);
    const div = container.firstChild as HTMLElement;
    expect(div.className).toContain("hidden");
    expect(div.className).toContain("print:block");
  });
});

describe("PrintFooter", () => {
  it("renders default footer text when no company provided", () => {
    render(<PrintFooter company={undefined} />);
    expect(screen.getByText("Generated by Payroll System")).toBeTruthy();
  });

  it("renders custom print footer from company", () => {
    render(
      <PrintFooter company={{ name: "Test", printFooter: "Confidential" }} />,
    );
    expect(screen.getByText("Confidential")).toBeTruthy();
  });

  it("renders a date string", () => {
    render(<PrintFooter company={undefined} />);
    expect(screen.getByText(new Date().toLocaleDateString())).toBeTruthy();
  });

  it("has hidden print:block class", () => {
    const { container } = render(<PrintFooter company={undefined} />);
    const div = container.firstChild as HTMLElement;
    expect(div.className).toContain("hidden");
    expect(div.className).toContain("print:block");
  });
});
