import type { CompanyInfo } from "./PayrollOutputView.types";

interface PrintHeaderProps {
  company?: CompanyInfo;
  payroll: { name: string; month: number; year: number };
  monthName: string;
}

export function PrintHeader({ company, payroll, monthName }: PrintHeaderProps) {
  return (
    <div className="hidden print:block mb-4 pb-2 border-b border-gray-200">
      <div className="text-center">
        <h2 className="text-lg font-semibold">{company?.name || "Company"}</h2>
        <p className="text-sm text-gray-600">{payroll.name}</p>
        <p className="text-sm text-gray-600">
          {monthName} {payroll.year}
        </p>
      </div>
    </div>
  );
}

interface PrintFooterProps {
  company?: CompanyInfo;
}

export function PrintFooter({ company }: PrintFooterProps) {
  return (
    <div className="hidden print:block mt-6 pt-2 border-t border-gray-200 text-xs text-gray-600">
      <div className="flex justify-between">
        <span>{company?.printFooter || "Generated by Payroll System"}</span>
        <span>{new Date().toLocaleDateString()}</span>
      </div>
    </div>
  );
}

// eslint-disable-next-line react-refresh/only-export-components
export function formatCurrency(value: number): string {
  return value.toLocaleString("en-US", {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  });
}
