import {
  Activity,
  ArrowDownToLine,
  ArrowUpFromLine,
  Banknote,
  BarChart3,
  Briefcase,
  Building2,
  Calendar,
  CalendarDays,
  CopyPlus,
  CreditCard,
  Database,
  FileText,
  Layers,
  LayoutDashboard,
  ListChecks,
  Lock,
  MapPin,
  Plus,
  Settings,
  ShieldCheck,
  Trash2,
  UserCog,
  Users,
} from "lucide-react";
import type { NavItem } from "./Sidebar.types";

export const navigation: NavItem[] = [
  {
    label: "Dashboard",
    icon: <LayoutDashboard className="w-4 h-4" />,
    path: "/",
  },
  {
    label: "Employees",
    icon: <Users className="w-4 h-4" />,
    department: "employees",
    children: [
      {
        label: "Employee Registry",
        icon: <Users className="w-4 h-4" />,
        path: "/employees",
        department: "employees",
        section: "employees",
      },
      {
        label: "Calendar",
        icon: <CalendarDays className="w-4 h-4" />,
        path: "/employees/calendar",
        department: "employees",
        section: "calendar",
      },
      {
        label: "Groups",
        icon: <Layers className="w-4 h-4" />,
        path: "/employees/groups",
        department: "employees",
        section: "groups",
      },
      {
        label: "Positions",
        icon: <Briefcase className="w-4 h-4" />,
        path: "/employees/positions",
        department: "employees",
        section: "positions",
      },
      {
        label: "Areas",
        icon: <MapPin className="w-4 h-4" />,
        path: "/employees/areas",
        department: "employees",
        section: "areas",
      },
    ],
  },
  {
    label: "Lists",
    icon: <ListChecks className="w-4 h-4" />,
    department: "lists",
    children: [
      {
        label: "Names",
        icon: <FileText className="w-4 h-4" />,
        path: "/lists/names",
        department: "lists",
        section: "names",
      },
      {
        label: "Benefits",
        icon: <Banknote className="w-4 h-4" />,
        path: "/lists/benefits",
        department: "lists",
        section: "benefits",
      },
      {
        label: "Earnings",
        icon: <ArrowUpFromLine className="w-4 h-4" />,
        path: "/lists/earnings",
        department: "lists",
        section: "earnings",
      },
      {
        label: "Deductions",
        icon: <ArrowDownToLine className="w-4 h-4" />,
        path: "/lists/deductions",
        department: "lists",
        section: "deductions",
      },
    ],
  },
  {
    label: "Payroll",
    icon: <CreditCard className="w-4 h-4" />,
    department: "payroll",
    children: [
      {
        label: "Payroll Runs",
        icon: <CreditCard className="w-4 h-4" />,
        path: "/payroll",
        department: "payroll",
        section: "payroll",
      },
      {
        label: "New Payroll",
        icon: <Plus className="w-4 h-4" />,
        path: "/payroll/new",
        department: "payroll",
        section: "payroll",
      },
      {
        label: "Templates",
        icon: <CopyPlus className="w-4 h-4" />,
        path: "/payroll/templates",
        department: "payroll",
        section: "templates",
      },
      {
        label: "Print Formats",
        icon: <FileText className="w-4 h-4" />,
        path: "/payroll/print-formats",
        department: "payroll",
        section: "templates",
      },
    ],
  },
  {
    label: "Reports",
    icon: <BarChart3 className="w-4 h-4" />,
    department: "reports",
    children: [
      {
        label: "13th Month",
        icon: <BarChart3 className="w-4 h-4" />,
        path: "/reports/13th-month",
        department: "reports",
        section: "13month",
      },
      {
        label: "Payroll Summary",
        icon: <BarChart3 className="w-4 h-4" />,
        path: "/reports/payroll-summary",
        department: "reports",
        section: "payroll",
      },
      {
        label: "Employee Master List",
        icon: <Users className="w-4 h-4" />,
        path: "/reports/employees",
        department: "reports",
        section: "employees",
      },
      {
        label: "Earnings/Deductions",
        icon: <BarChart3 className="w-4 h-4" />,
        path: "/reports/earnings-deductions",
        department: "reports",
        section: "payroll",
      },
      {
        label: "Attendance",
        icon: <BarChart3 className="w-4 h-4" />,
        path: "/reports/attendance",
        department: "reports",
        section: "attendance",
      },
      {
        label: "Benefits Utilization",
        icon: <BarChart3 className="w-4 h-4" />,
        path: "/reports/benefits-utilization",
        department: "reports",
        section: "payroll",
      },
      {
        label: "Year-End",
        icon: <BarChart3 className="w-4 h-4" />,
        path: "/reports/year-end",
        department: "reports",
        section: "payroll",
      },
    ],
  },
  {
    label: "System",
    icon: <Settings className="w-4 h-4" />,
    department: "system",
    children: [
      {
        label: "Companies",
        icon: <Building2 className="w-4 h-4" />,
        path: "/system/companies",
        department: "system",
        section: "companies",
      },
      {
        label: "Company Settings",
        icon: <Settings className="w-4 h-4" />,
        path: "/system/company-settings",
        department: "system",
        section: "companies",
      },
      {
        label: "Calendar",
        icon: <Calendar className="w-4 h-4" />,
        path: "/system/calendar",
        department: "system",
        section: "calendar",
      },
      {
        label: "Terms",
        icon: <FileText className="w-4 h-4" />,
        path: "/system/terms",
        department: "system",
        section: "terms",
      },
      {
        label: "Users",
        icon: <UserCog className="w-4 h-4" />,
        path: "/system/users",
        department: "system",
        section: "users",
      },
      {
        label: "Restrictions",
        icon: <ShieldCheck className="w-4 h-4" />,
        path: "/system/restrictions",
        department: "system",
        section: "users",
      },
      {
        label: "Audit Log",
        icon: <Lock className="w-4 h-4" />,
        path: "/system/audit",
        department: "system",
        section: "audit",
      },
      {
        label: "Database",
        icon: <Database className="w-4 h-4" />,
        path: "/system/database",
        department: "system",
        section: "database",
      },
      {
        label: "Settings",
        icon: <Settings className="w-4 h-4" />,
        path: "/system/settings",
        department: "system",
        section: "companies",
      },
      {
        label: "Trash",
        icon: <Trash2 className="w-4 h-4" />,
        path: "/system/trash",
        department: "system",
        section: "companies",
      },
      {
        label: "Health Check",
        icon: <Activity className="w-4 h-4" />,
        path: "/system/health",
        department: "system",
        section: "database",
      },
      {
        label: "Activity Monitor",
        icon: <Activity className="w-4 h-4" />,
        path: "/system/activity",
        department: "system",
        section: "users",
      },
    ],
  },
];
